version: '3.8'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=symfony
      - MARIADB_DATABASE=symfony
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/bitnami/mariadb

  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:9000'
    environment:
      - SYMFONY_DATABASE_HOST=mariadb
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=symfony
      - SYMFONY_DATABASE_NAME=symfony
    volumes:
      - '.:/var/www/html'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
